services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres00
      POSTGRES_DB: labkeeper
    ports:
      - 5432:5432