export const SEQUELIZE = 'SEQUELIZE';
export const REPOSITORIES = {
  HOST_REPOSITORY: 'HOST_REPOSITORY',
  SERVICE_REPOSITORY: 'SERVICE_REPOSITORY',
  IP_ADDRESS_REPOSITORY: 'IP_ADDRESS_REPOSITORY',
  USER_REPOSITORY: 'USER_REPOSITORY'
} as const;
